### ISSUE TITLE
invalid CTCP PING response

### ISSUE THREAD

**Issue by duckinator** [nixeagle/nisp#3]
if i send:
PRIVMSG nisp :PING 1

it replies with:
:nisp!lisp@b193c6.6039c8.fc7a36.1dacf7 NOTICE foobar :PING PING 1

Must i really explain where the fail is?

**Comment by nixeagle** [comment]
Ok, this is a cl-irc bug, I'll look at this over the next day or so and patch (likely) cl-irc and update that submodule reference.
